# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: UT&IT tests

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: sas
    - name: Setup db
        uses: mysql -u root -p root sas < ./src/main/resources/initDb.sql
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Maven clean
      run: mvn clean
    - name: Maven install
      run: mvn install





